export const TRANSLATIONS = {
  bonus: '보너스',
  debt: '부채',
  etc: '기타',
  in_cash: '현금 수입',
  interest: '이자',
  mature: '만기',
  salary: '급여',
  side_job: '부업',

  book: '도서',
  car: '자동차',
  clothes: '의류',
  cosmetics: '화장품',
  delivery: '배달',
  drink: '음료',
  drinking: '술',
  entertainment: '여가/오락',
  exercise: '운동',
  house: '주거',
  loan: '대출',
  maintenance_cost: '관리비',
  meal: '식사',
  medical: '의료',
  necessities: '생필품',
  out_cash: '현금 지출',
  pet: '반려동물',
  phone_bill: '통신비',
  present: '선물',
  public_transport: '교통',
  shopping: '쇼핑',
  study: '학습',
}

